name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
            - lable-1  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Check Node.js version
      run: node -v

    - name: Check npm version
      run: npm -v

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Build the React app
      run: npm run build

    - name: Ensure build directory exists
      run: test -d build || echo "Build directory not found!"

    - name: Capture the build output
      run: |
        mkdir -p output
        cp -r ./build/* output/

    - name: Archive the output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: output/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build


